version: "3.9"

services:
  reverse-proxy:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"     # en prod: 80/443 (TLS ensuite)
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - guematrix-frontend
      - db-api-node
      - guematrix-backend
    networks:
      - internal

  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: torahpass
      POSTGRES_DB: torah_gematria
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    expose:
      - "5432"
    networks:
      - internal

  db-api-node:
    build: ./db-api-node
    depends_on:
      - postgres
    restart: unless-stopped
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: torahpass
      DB_NAME: torah_gematria
    expose:
      - "3001"
    networks:
      - internal

  guematrix-backend:
    build: ./guematrixbackend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: torahpass
      DB_NAME: torah_gematria
    expose:
      - "8085"
    networks:
      - internal

  guematrix-frontend:
    build: ./guematrix-frontend
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - internal

networks:
  internal:
    driver: bridge
